version: '3.8'

services:
  docling:
    image: quay.io/docling-project/docling-serve:latest
    container_name: docling-server
    ports:
      - "5001:5001"
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount a directory for input documents
      - ./documents:/app/documents:ro
      # Optional: Mount a directory for output
      - ./output:/app/output
